version: 2.1

jobs:
  build_and_test:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test

    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: Copy database.yml
          command: |
            cp .circleci/database.yml config/database.yml
      - run: sudo apt update --fix-missing
      - run: sudo apt install -y postgresql-client || true
      - run: sudo apt install cmake
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3
      - run:
          name: Database Setup
          command: |
            bundle exec rake db:setup
      - run:
          name: Test suite
          command: bundle exec rake
      - run:
          name: Brakeman
          command: bundle exec brakeman
      - run:
          name: Test suite
          command: bundle audit
workflows:
  build_and_test:
    jobs:
      - build_and_test
