default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: pseudonymisation_service
  password: ps3ud0nym1s4t10n_s3rv1c3

development:
  <<: *default
  database: pseudonymisation_service_development

test:
  <<: *default
  database: pseudonymisation_service_test

production:
  <<: *default
  database: pseudonymisation_service_production
  username: <%# Rails.application.credentials.database[:username] %>
  password: <%# Rails.application.credentials.database[:password] %>
