name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: rails_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USERNAME: rails
      DB_PASSWORD: rails_password

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
    - name: Install dependencies
      run: bundle install
    - name: Inject configuration
      run: cp config/database.yml{.ci,}
    - name: Prepare the database
      run: bin/rails db:setup
    - name: Run tests
      run: bin/rails test

  brakeman:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
    - name: Install dependencies
      run: bundle install
    - name: Run Brakeman analysis
      run: bundle exec brakeman

  bundle-audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
    - name: Install dependencies
      run: bundle install
    - name: Audit the bundle
      run: bundle exec bundle-audit check --update

  notify:
    # Run only on master, but regardless of whether tests past:
    if: ${{ always() && github.ref == 'refs/heads/master' }}

    needs:
      - test
      - brakeman
      - bundle-audit

    runs-on: ubuntu-latest

    steps:
    - uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: workflow,commit,author
        custom_payload: |
          {
            channel: 'CSCHWSP53',
            username: 'CI',
            icon_emoji: ':hammer_and_wrench:',
            attachments: [{
              color: '${{ needs.test.result }}' === 'success' ? 'good' : '${{ needs.test.result }}' === 'failure' ? 'danger' : 'warning',
              text: `${process.env.AS_WORKFLOW} against \`${{ github.ref }}\` (${process.env.AS_COMMIT}) for ${{ github.actor }} resulted in *${{ needs.test.result }}*.`
            },{
              color: '${{ needs.brakeman.result }}' === 'success' ? 'good' : '${{ needs.brakeman.result }}' === 'failure' ? 'danger' : 'warning',
              text: `Brakeman checks returned *${{ needs.brakeman.result }}*.`
            },{
              color: '${{ needs.bundle-audit.result }}' === 'success' ? 'good' : '${{ needs.bundle-audit.result }}' === 'failure' ? 'danger' : 'warning',
              text: `Bundle Audit checks returned *${{ needs.bundle-audit.result }}*.`
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
